const TEST_TYPES = {
  SUPERADMIN: "SUPERADMIN_TEST",
  INSTITUTE_ADMIN: "INSTITUTE_ADMIN_TEST",
  BRANCH_ADMIN: "BRANCH_ADMIN_TEST",
  TEACHER: "TEACHER_TEST",
  PRACTICE: "PRACTICE_TEST",
};

const TEST_STATUS = {
  PENDING: "PENDING",
  CREATED: "CREATED",
  ASSIGNED: "ASSIGNED",
};

module.exports = { TEST_TYPES, TEST_STATUS };
