const USER_ROLES = {
  SUPER_ADMIN: "superAdmin",
  INSTITUTE_ADMIN: "instituteAdmin",
  BRANCH_ADMIN: "branchAdmin",
  STAFF: "staff",
  TEACHER: "teacher",
  STUDENT: "student",
};

const STUDENT_FIELDS = [
  { field: "admissionNo", type: "string" },
  { field: "username", type: "string" },
  { field: "profileImage", type: "file" },
  { field: "firstName", type: "string" },
  { field: "lastName", type: "string" },
  { field: "role", type: "string" },
  { field: "instituteId", type: "objectId" },
  { field: "branchId", type: "objectId" },
  { field: "batchId", type: "objectId" },
  { field: "isActive", type: "boolean" },
  { field: "gender", type: "string" },
  { field: "mobile", type: "string" },
  { field: "email", type: "string" },
  { field: "profileImage", type: "string" },
  { field: "dob", type: "date" },
  { field: "nationality", type: "string" },
  { field: "aadharNo", type: "string" },
  { field: "address", type: "string" },
  { field: "city", type: "string" },
  { field: "pincode", type: "string" },
  { field: "parentMobile", type: "string" },
  { field: "fatherName", type: "string" },
  { field: "motherName", type: "string" },
  { field: "community", type: "string" },
  { field: "registrationType", type: "string" },
  { field: "satsNo", type: "string" },
  { field: "dateOfJoining", type: "date" },
  { field: "password", type: "string" },
];

const TEACHER_FIELDS = [
  { field: "username", type: "string" },
  { field: "firstName", type: "string" },
  { field: "lastName", type: "string" },
  { field: "isActive", type: "boolean" },
  { field: "gender", type: "string" },
  { field: "instituteId", type: "objectId" },
  { field: "role", type: "string" },
  { field: "email", type: "string" },
  { field: "mobile", type: "string" },
  { field: "profileImage", type: "file" },
  { field: "dob", type: "date" },
  { field: "bloodGroup", type: "string" },
  { field: "aadharNo", type: "string" },
  { field: "panNumber", type: "string" },
  { field: "address", type: "string" },
  { field: "city", type: "string" },
  { field: "pincode", type: "string" },
  { field: "emergencyContactNumber", type: "string" },
  { field: "bankName", type: "string" },
  { field: "bankIfsc", type: "string" },
  { field: "bankAccountNo", type: "string" },
  { field: "pfAccountNumber", type: "string" },
  { field: "epsAccountNumber", type: "string" },
  { field: "dateOfJoining", type: "date" },
  { field: "contractStartDate", type: "date" },
  { field: "contractType", type: "string" },
  { field: "experience", type: "string" },
  { field: "designation", type: "string" },
  { field: "department", type: "string" },
  { field: "previousInstituteName", type: "string" },
  { field: "collegeName", type: "string" },
  { field: "collegeCityName", type: "string" },
  { field: "educationalBackground", type: "string" },
  { field: "password", type: "string" },
];

module.exports = { USER_ROLES, STUDENT_FIELDS, TEACHER_FIELDS };
