const mongoose = require("mongoose");

const profileSchema = new mongoose.Schema(
  {
    dob: { type: Date },
    bloodGroup: { type: String },
    nationality: { type: String },
    religion: { type: String },
    aadharNo: { type: String },
    panNumber: { type: String },
    passportNo: { type: String },
    passportExpiry: { type: Date },
    address: { type: String },
    city: { type: String },
    state: { type: String },
    pincode: { type: String },
    countryOfIssue: { type: String },
    emergencyContactNumber: { type: String },
    emergnecyContactPerson: { type: String },
    parentMobile: { type: String },
    spouseName: { type: String },
    fatherName: { type: String },
    motherName: { type: String },
    fatherMobile: { type: String },
    bankName: { type: String },
    bankBranch: { type: String },
    bankIfsc: { type: String },
    bankAccountNo: { type: String },
    pfAccountNumber: { type: String },
    epsAccountNumber: { type: String },
    community: { type: String },
    registrationType: { type: String },
    remarks: { type: String },
    satsNo: { type: String },
    dateOfJoining: { type: Date },
    contractStartDate: { type: Date },
    contractType: { type: String },
    experience: { type: String },
    feesPaid: { type: Number },
    completionYear: { type: Date },
    academicYear: { type: String },
    class: { type: String },
    hostelId: { type: String },
    transportationId: { type: String },
    roomType: { type: String },
    from: { type: String },
    to: { type: String },
    designation: { type: String },
    department: { type: String },
    previousInstituteName: { type: String },
    collegeName: { type: String },
    collegeCityName: { type: String },
    rollNo: { type: String },
    emergencyContactPerson: { type: String },
    year: { type: String },
    caste: { type: String },
    areaName: { type: String },
    educationalBackground: { type: String },
  },
  {
    timestamps: true,
  }
);

const Profile = mongoose.model("Profile", profileSchema);

module.exports = Profile;
